In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Student Marks Analysis

In [2]:
dic={'Name':['Priyang','Aadhya','Krisha','Vedant','Parshv','Mittal','Archana'],
     'Marks':[98,89,99,87,90,83,99],
     'Gender':['Male','Female','Female','Male','Male','Female','Female']}
df=pd.DataFrame(dic)
print(df)

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [ ]:
#1.Display top 3 rows

In [3]:
df.head(3)

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female

In [ ]:
#2.Display last 3 rows

In [4]:
df.tail(3)

      Name  Marks  Gender
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [ ]:
#3.Find shape of dataset

In [5]:
df.shape

(7, 3)

In [6]:
print('Number of rows',df.shape[0])
print('Number of column',df.shape[1])

Number of rows 7
Number of column 3

In [ ]:
#4.Give info of dataset

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [ ]:
#5.Check null values

In [8]:
df.isnull()

    Name  Marks  Gender
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False
4  False  False   False
5  False  False   False
6  False  False   False

In [9]:
df.isnull().sum()

Name      0
Marks     0
Gender    0
dtype: int64

In [ ]:
#6.Get overall statistics

In [10]:
df.describe()

           Marks
count   7.000000
mean   92.142857
std     6.491753
min    83.000000
25%    88.000000
50%    90.000000
75%    98.500000
max    99.000000

In [ ]:
#7.Find unique values from gender column.

In [11]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [ ]:
#8.Find number of unique values from gender column.

In [12]:
df['Gender'].nunique()

2

In [ ]:
#9.Find count of unique values.

In [13]:
df['Gender'].value_counts()

Gender
Female    4
Male      3
Name: count, dtype: int64

In [ ]:
#10.Find number of students having marks between 90 to 100.

In [14]:
df['Marks']>=90

0     True
1    False
2     True
3    False
4     True
5    False
6     True
Name: Marks, dtype: bool

In [15]:
df[df['Marks']>=90]

      Name  Marks  Gender
0  Priyang     98    Male
2   Krisha     99  Female
4   Parshv     90    Male
6  Archana     99  Female

In [17]:
df[(df['Marks']>=90) & (df['Marks']<=100)]

      Name  Marks  Gender
0  Priyang     98    Male
2   Krisha     99  Female
4   Parshv     90    Male
6  Archana     99  Female

In [18]:
len(df[(df['Marks']>=90) & (df['Marks']<=100)])

4

In [21]:
sum(df['Marks'].between(90,100))

4

In [ ]:
#11.Find average,min,max marks

In [22]:
df['Marks'].mean()

np.float64(92.14285714285714)

In [23]:
df['Marks'].min()

83

In [24]:
df['Marks'].max()

99

In [ ]:
#12.Apply method

In [25]:
def marks(x):
  return x/2

In [26]:
df['Marks'].apply(marks)

0    49.0
1    44.5
2    49.5
3    43.5
4    45.0
5    41.5
6    49.5
Name: Marks, dtype: float64

In [27]:
df['Half_marks']=df['Marks'].apply(marks)

In [28]:
df

      Name  Marks  Gender  Half_marks
0  Priyang     98    Male        49.0
1   Aadhya     89  Female        44.5
2   Krisha     99  Female        49.5
3   Vedant     87    Male        43.5
4   Parshv     90    Male        45.0
5   Mittal     83  Female        41.5
6  Archana     99  Female        49.5

In [29]:
df['Marks'].apply(lambda x:x/2)

0    49.0
1    44.5
2    49.5
3    43.5
4    45.0
5    41.5
6    49.5
Name: Marks, dtype: float64

In [ ]:
#13.Find length of name

In [30]:
df['Name'].apply(len)

0    7
1    6
2    6
3    6
4    6
5    6
6    7
Name: Name, dtype: int64

In [ ]:
#14.Drop the column

In [31]:
df

      Name  Marks  Gender  Half_marks
0  Priyang     98    Male        49.0
1   Aadhya     89  Female        44.5
2   Krisha     99  Female        49.5
3   Vedant     87    Male        43.5
4   Parshv     90    Male        45.0
5   Mittal     83  Female        41.5
6  Archana     99  Female        49.5

In [32]:
df.drop(['Half_marks'],axis=1)

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [ ]:
#15.Print name of the columns.

In [33]:
df.columns

Index(['Name', 'Marks', 'Gender', 'Half_marks'], dtype='object')

In [ ]:
#16.Sort the dataframe according to marks.

In [34]:
df.sort_values(by=['Marks'])

      Name  Marks  Gender  Half_marks
5   Mittal     83  Female        41.5
3   Vedant     87    Male        43.5
1   Aadhya     89  Female        44.5
4   Parshv     90    Male        45.0
0  Priyang     98    Male        49.0
2   Krisha     99  Female        49.5
6  Archana     99  Female        49.5

In [35]:
df.sort_values(by=['Marks'],ascending=False)

      Name  Marks  Gender  Half_marks
2   Krisha     99  Female        49.5
6  Archana     99  Female        49.5
0  Priyang     98    Male        49.0
4   Parshv     90    Male        45.0
1   Aadhya     89  Female        44.5
3   Vedant     87    Male        43.5
5   Mittal     83  Female        41.5

In [ ]:
#17.Display Name & Marks of the female stuednts.

In [36]:
df[df['Gender']=='Female'][['Name','Marks']]

      Name  Marks
1   Aadhya     89
2   Krisha     99
5   Mittal     83
6  Archana     99